Fixed Error Site Page
bitmovin/bitmovin-analytics-sample-dashboard pull request #22
Opened 2018-08-16 12:17 UTC by paulk4633

2018-08-17 09:53 UTC, peterpf commented on package.json
> +    "redux-router": "^2.1.2",
Not required, we already have `react-router`

2018-08-17 09:56 UTC, peterpf requested changes
See comments, nice work :+1:

2018-08-20 07:16 UTC, peterpf approved these changes

2018-08-20 08:33 UTC, Tigraine approved these changes

2018-08-20 08:34 UTC, merged